<?xml version="1.0"?>
<!--
  MOBILE ARM URDF - 6-DOF Robotic Manipulator
  ============================================

  DESCRIPTION:
    Modular URDF for 6-DOF robotic arm with gripper
    5 arm joints (revolute) + 1 gripper joint

  USAGE:
    <xacro:include filename="mobile_arm.urdf.xacro"/>
    <xacro:mobile_arm prefix="arm_" parent="body_link">
      <origin xyz="0 0 0.2" rpy="0 0 0"/>
    </xacro:mobile_arm>

  JOINTS:
    - joint_1: Base rotation (Z-axis)
    - joint_2: Shoulder (Y-axis)
    - joint_3: Elbow (Y-axis)
    - joint_4: Wrist (Y-axis)
    - gripper_base_joint: Gripper rotation
    - left_gear_joint: Gripper open/close
-->

<robot name="mobile_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ================================================================ -->
  <!-- MACRO DEFINITION -->
  <!-- ================================================================ -->

  <xacro:macro name="mobile_arm" params="prefix parent *origin">

    <!-- ============================================================== -->
    <!-- PARAMETERS -->
    <!-- ============================================================== -->


    <!-- Arm dimensions (simplified) -->
    <xacro:property name="arm_base_height" value="0.056"/>
    <xacro:property name="link1_length" value="0.08"/>
    <xacro:property name="link2_length" value="0.12"/>
    <xacro:property name="link3_length" value="0.10"/>
    <xacro:property name="link4_length" value="0.08"/>
    <xacro:property name="gripper_length" value="0.06"/>

    <!-- Masses (from original URDF) -->
    <xacro:property name="base_mass" value="0.094"/>
    <xacro:property name="link1_mass" value="0.072"/>
    <xacro:property name="link2_mass" value="0.057"/>
    <xacro:property name="link3_mass" value="0.057"/>
    <xacro:property name="link4_mass" value="0.045"/>
    <xacro:property name="gripper_mass" value="0.030"/>

    <!-- ============================================================== -->
    <!-- INERTIA MACROS -->
    <!-- ============================================================== -->

    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia ixx="${m*(3*r*r+h*h)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${m*(3*r*r+h*h)/12.0}" iyz="0.0"
               izz="${m*r*r/2.0}"/>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m x y z">
      <inertia ixx="${m*(y*y+z*z)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${m*(x*x+z*z)/12.0}" iyz="0.0"
               izz="${m*(x*x+y*y)/12.0}"/>
    </xacro:macro>

    <!-- ============================================================== -->
    <!-- ARM BASE JOINT -->
    <!-- ============================================================== -->

    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}base_link"/>
    </joint>

    <!-- ============================================================== -->
    <!-- ARM LINKS AND JOINTS -->
    <!-- ============================================================== -->

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/arm_base_link.STL"/>
        </geometry>
        <material name="arm_material">
          <color rgba="0.8 0.8 0.9 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/arm_base_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <xacro:cylinder_inertia m="${base_mass}" r="0.04" h="${arm_base_height}"/>
      </inertial>
    </link>

    <!-- Joint 1 (Base Rotation) -->
    <joint name="${prefix}joint_1" type="revolute">
      <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1"/>
      <axis xyz="0 0 1"/>  <!-- Z-axis rotation -->
      <limit lower="${-pi}" upper="${pi}" effort="10.0" velocity="2.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <!-- Link 1 -->
    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_1.STL"/>
        </geometry>
        <material name="arm_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_1.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
        <mass value="${link1_mass}"/>
        <xacro:cylinder_inertia m="${link1_mass}" r="0.03" h="${link1_length}"/>
      </inertial>
    </link>

    <!-- Joint 2 (Shoulder) -->
    <joint name="${prefix}joint_2" type="revolute">
      <origin xyz="0.014 0 0.040" rpy="0 0 0"/>
      <parent link="${prefix}link_1"/>
      <child link="${prefix}link_2"/>
      <axis xyz="0 1 0"/>  <!-- Y-axis rotation -->
      <limit lower="${-pi/2}" upper="${pi/2}" effort="10.0" velocity="2.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <!-- Link 2 -->
    <link name="${prefix}link_2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_2.STL"/>
        </geometry>
        <material name="arm_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_2.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
        <mass value="${link2_mass}"/>
        <xacro:cylinder_inertia m="${link2_mass}" r="0.025" h="${link2_length}"/>
      </inertial>
    </link>

    <!-- Joint 3 (Elbow) -->
    <joint name="${prefix}joint_3" type="revolute">
      <origin xyz="0 -0.0094 0.115" rpy="0 0 0"/>
      <parent link="${prefix}link_2"/>
      <child link="${prefix}link_3"/>
      <axis xyz="0 1 0"/>  <!-- Y-axis rotation -->
      <limit lower="${-pi/2}" upper="${pi/2}" effort="10.0" velocity="2.0"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <!-- Link 3 -->
    <link name="${prefix}link_3">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_3.STL"/>
        </geometry>
        <material name="arm_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_3.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="${link3_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <mass value="${link3_mass}"/>
        <xacro:cylinder_inertia m="${link3_mass}" r="0.02" h="${link3_length}"/>
      </inertial>
    </link>

    <!-- Joint 4 (Wrist) -->
    <joint name="${prefix}joint_4" type="revolute">
      <origin xyz="0.090 0.025 0" rpy="0 0 0"/>
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <axis xyz="0 1 0"/>  <!-- Y-axis rotation -->
      <limit lower="${-pi/2}" upper="${pi/2}" effort="5.0" velocity="2.0"/>
      <dynamics damping="0.3" friction="0.1"/>
    </joint>

    <!-- Link 4 -->
    <link name="${prefix}link_4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_4.STL"/>
        </geometry>
        <material name="arm_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/link_4.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
        <mass value="${link4_mass}"/>
        <xacro:cylinder_inertia m="${link4_mass}" r="0.02" h="${link4_length}"/>
      </inertial>
    </link>

    <!-- Gripper Base Joint -->
    <joint name="${prefix}gripper_base_joint" type="revolute">
      <origin xyz="0 0.021 0.068" rpy="0 0 0"/>
      <parent link="${prefix}link_4"/>
      <child link="${prefix}gripper_base_link"/>
      <axis xyz="0 0 1"/>  <!-- Z-axis rotation -->
      <limit lower="${-pi}" upper="${pi}" effort="5.0" velocity="2.0"/>
      <dynamics damping="0.3" friction="0.1"/>
    </joint>

    <!-- Gripper Base Link -->
    <link name="${prefix}gripper_base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/gripper_base_link.STL"/>
        </geometry>
        <material name="gripper_material">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/gripper_base_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${gripper_mass}"/>
        <xacro:box_inertia m="${gripper_mass}" x="0.04" y="0.04" z="0.04"/>
      </inertial>
    </link>

    <!-- Left Gear Joint (Gripper Control) -->
    <joint name="${prefix}left_gear_joint" type="revolute">
      <origin xyz="0.010366 0 0.015" rpy="0 0 0"/>
      <parent link="${prefix}gripper_base_link"/>
      <child link="${prefix}left_gear_link"/>
      <axis xyz="0 1 0"/>  <!-- Y-axis rotation -->
      <limit lower="0" upper="${pi/4}" effort="5.0" velocity="1.0"/>
      <dynamics damping="0.2" friction="0.05"/>
    </joint>

    <!-- Left Gear Link -->
    <link name="${prefix}left_gear_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/left_gear_link.STL"/>
        </geometry>
        <material name="gripper_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/left_gear_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <xacro:box_inertia m="0.01" x="0.02" y="0.02" z="0.01"/>
      </inertial>
    </link>

    <!-- Left Link (Gripper Finger) -->
    <joint name="${prefix}left_link_joint" type="fixed">
      <origin xyz="0.010078 0 0.028" rpy="0 0 0"/>
      <parent link="${prefix}left_gear_link"/>
      <child link="${prefix}left_link"/>
    </joint>

    <link name="${prefix}left_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/left_link.STL"/>
        </geometry>
        <material name="gripper_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/left_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.005"/>
        <xacro:box_inertia m="0.005" x="0.01" y="0.01" z="0.03"/>
      </inertial>
    </link>

    <!-- Left Finger -->
    <joint name="${prefix}left_finger_joint" type="fixed">
      <origin xyz="0.009 0 0.036" rpy="0 0 0"/>
      <parent link="${prefix}left_link"/>
      <child link="${prefix}left_finger_link"/>
    </joint>

    <link name="${prefix}left_finger_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/left_finger_link.STL"/>
        </geometry>
        <material name="gripper_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/left_finger_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.003"/>
        <xacro:box_inertia m="0.003" x="0.01" y="0.01" z="0.02"/>
      </inertial>
    </link>

    <!-- Right Side Gripper (Mirrored) -->
    <joint name="${prefix}right_gear_joint" type="revolute">
      <origin xyz="-0.010366 0 0.015" rpy="0 0 0"/>
      <parent link="${prefix}gripper_base_link"/>
      <child link="${prefix}right_gear_link"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-pi/4}" upper="0" effort="5.0" velocity="1.0"/>
      <dynamics damping="0.2" friction="0.05"/>
      <!-- Mimic left gear for synchronized gripper -->
      <mimic joint="${prefix}left_gear_joint" multiplier="-1" offset="0"/>
    </joint>

    <link name="${prefix}right_gear_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/right_gear_link.STL"/>
        </geometry>
        <material name="gripper_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/right_gear_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <xacro:box_inertia m="0.01" x="0.02" y="0.02" z="0.01"/>
      </inertial>
    </link>

    <joint name="${prefix}right_link_joint" type="fixed">
      <origin xyz="-0.010078 0 0.028" rpy="0 0 0"/>
      <parent link="${prefix}right_gear_link"/>
      <child link="${prefix}right_link"/>
    </joint>

    <link name="${prefix}right_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/right_link.STL"/>
        </geometry>
        <material name="gripper_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/right_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.005"/>
        <xacro:box_inertia m="0.005" x="0.01" y="0.01" z="0.03"/>
      </inertial>
    </link>

    <joint name="${prefix}right_finger_joint" type="fixed">
      <origin xyz="-0.009 0 0.036" rpy="0 0 0"/>
      <parent link="${prefix}right_link"/>
      <child link="${prefix}right_finger_link"/>
    </joint>

    <link name="${prefix}right_finger_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/right_finger_link.STL"/>
        </geometry>
        <material name="gripper_material"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mobile_manipulator_bringup/meshes/right_finger_link.STL"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.003"/>
        <xacro:box_inertia m="0.003" x="0.01" y="0.01" z="0.02"/>
      </inertial>
    </link>

  </xacro:macro>


</robot>
