<?xml version="1.0"?>
<!--
  MOBILE BASE URDF - Four-Wheel Differential Drive Platform
  ===========================================================

  DESCRIPTION:
    Modular URDF for 4-wheel differential drive mobile base
    Includes wheels, sensors (lidar, camera), and mounting point for arm

  USAGE:
    <xacro:include filename="mobile_base.urdf.xacro"/>
    <xacro:mobile_base prefix=""/>

  FRAMES:
    - body_link: Main chassis frame
    - wheel joints: 4x continuous joints for wheels
    - lidar_link: Laser scanner mount
    - camera_link: RGB camera mount
    - arm_mount_link: Mounting point for robotic arm
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ================================================================ -->
  <!-- MACRO DEFINITION -->
  <!-- ================================================================ -->

  <xacro:macro name="mobile_base" params="prefix:=''">

    <!-- ============================================================== -->
    <!-- PARAMETERS -->
    <!-- ============================================================== -->

    <!-- Chassis dimensions (meters) -->
    <xacro:property name="chassis_length" value="0.5"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="chassis_mass" value="20.0"/>

    <!-- Wheel dimensions (meters) -->
    <xacro:property name="wheel_radius" value="0.075"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="wheel_mass" value="2.5"/>
    <xacro:property name="wheel_offset_x" value="0.15"/>   <!-- Front/back from center -->
    <xacro:property name="wheel_offset_y" value="0.175"/>  <!-- Left/right from center -->
    <xacro:property name="wheel_offset_z" value="-0.07"/>  <!-- Vertical from chassis -->

    <!-- Sensor dimensions -->
    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_height" value="0.06"/>
    <xacro:property name="lidar_mass" value="0.5"/>

    <xacro:property name="camera_width" value="0.05"/>
    <xacro:property name="camera_height" value="0.05"/>
    <xacro:property name="camera_depth" value="0.05"/>
    <xacro:property name="camera_mass" value="0.2"/>

    <!-- Material density for calculations -->

    <!-- ============================================================== -->
    <!-- INERTIA MACROS -->
    <!-- ============================================================== -->

    <!-- Box inertia macro -->
    <xacro:macro name="box_inertia" params="m x y z">
      <inertia ixx="${m*(y*y+z*z)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${m*(x*x+z*z)/12.0}" iyz="0.0"
               izz="${m*(x*x+y*y)/12.0}"/>
    </xacro:macro>

    <!-- Cylinder inertia macro (axis along z) -->
    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia ixx="${m*(3*r*r+h*h)/12.0}" ixy="0.0" ixz="0.0"
               iyy="${m*(3*r*r+h*h)/12.0}" iyz="0.0"
               izz="${m*r*r/2.0}"/>
    </xacro:macro>

    <!-- ============================================================== -->
    <!-- BASE LINK (CHASSIS) -->
    <!-- ============================================================== -->

    <link name="${prefix}body_link">
      <!-- Visual -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="chassis_material">
          <color rgba="0.8 0.1 0.1 1.0"/>  <!-- Red -->
        </material>
      </visual>

      <!-- Collision -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
      </collision>

      <!-- Inertial -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${chassis_mass}"/>
        <xacro:box_inertia m="${chassis_mass}"
                           x="${chassis_length}"
                           y="${chassis_width}"
                           z="${chassis_height}"/>
      </inertial>
    </link>

    <!-- ============================================================== -->
    <!-- WHEELS (4x) -->
    <!-- ============================================================== -->

    <!-- Wheel macro for reusability -->
    <xacro:macro name="wheel" params="prefix side_prefix reflect_y reflect_x">

      <!-- Joint -->
      <joint name="${prefix}${side_prefix}_joint" type="continuous">
        <parent link="${prefix}body_link"/>
        <child link="${prefix}${side_prefix}_link"/>
        <origin xyz="${reflect_x*wheel_offset_x} ${reflect_y*wheel_offset_y} ${wheel_offset_z}"
                rpy="0 0 0"/>
        <axis xyz="0 1 0"/>  <!-- Rotation axis (y-axis for wheels) -->
        <limit effort="1000.0" velocity="100.0"/>
        <dynamics damping="1.0" friction="1.0"/>
      </joint>

      <!-- Link -->
      <link name="${prefix}${side_prefix}_link">
        <!-- Visual -->
        <visual>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>  <!-- Rotate to align cylinder -->
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="wheel_material">
            <color rgba="0.2 0.2 0.2 1.0"/>  <!-- Dark gray -->
          </material>
        </visual>

        <!-- Collision -->
        <collision>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>

        <!-- Inertial -->
        <inertial>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <mass value="${wheel_mass}"/>
          <xacro:cylinder_inertia m="${wheel_mass}"
                                  r="${wheel_radius}"
                                  h="${wheel_width}"/>
        </inertial>
      </link>

    </xacro:macro>

    <!-- Instantiate 4 wheels -->
    <xacro:wheel prefix="${prefix}" side_prefix="front_right" reflect_y="-1" reflect_x="1"/>
    <xacro:wheel prefix="${prefix}" side_prefix="front_left"  reflect_y="1"  reflect_x="1"/>
    <xacro:wheel prefix="${prefix}" side_prefix="back_right"  reflect_y="-1" reflect_x="-1"/>
    <xacro:wheel prefix="${prefix}" side_prefix="back_left"   reflect_y="1"  reflect_x="-1"/>

    <!-- ============================================================== -->
    <!-- LIDAR SENSOR -->
    <!-- ============================================================== -->

    <joint name="${prefix}lidar_joint" type="fixed">
      <parent link="${prefix}body_link"/>
      <child link="${prefix}lidar_link"/>
      <origin xyz="0 0 ${chassis_height/2 + lidar_height/2 + 0.01}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}lidar_link">
      <!-- Visual -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
        <material name="lidar_material">
          <color rgba="0.1 0.1 0.1 1.0"/>  <!-- Black -->
        </material>
      </visual>

      <!-- Collision -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
        </geometry>
      </collision>

      <!-- Inertial -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${lidar_mass}"/>
        <xacro:cylinder_inertia m="${lidar_mass}"
                                r="${lidar_radius}"
                                h="${lidar_height}"/>
      </inertial>
    </link>

    <!-- Laser frame (for sensor data) -->
    <joint name="${prefix}laser_frame_joint" type="fixed">
      <parent link="${prefix}lidar_link"/>
      <child link="${prefix}laser_frame"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}laser_frame"/>

    <!-- ============================================================== -->
    <!-- CAMERA SENSOR -->
    <!-- ============================================================== -->

    <joint name="${prefix}camera_joint" type="fixed">
      <parent link="${prefix}body_link"/>
      <child link="${prefix}camera_link"/>
      <origin xyz="${chassis_length/2 + camera_depth/2} 0 ${chassis_height/2 - 0.02}"
              rpy="0 0 0"/>
    </joint>

    <link name="${prefix}camera_link">
      <!-- Visual -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_depth} ${camera_width} ${camera_height}"/>
        </geometry>
        <material name="camera_material">
          <color rgba="0.2 0.2 0.8 1.0"/>  <!-- Blue -->
        </material>
      </visual>

      <!-- Collision -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_depth} ${camera_width} ${camera_height}"/>
        </geometry>
      </collision>

      <!-- Inertial -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${camera_mass}"/>
        <xacro:box_inertia m="${camera_mass}"
                           x="${camera_depth}"
                           y="${camera_width}"
                           z="${camera_height}"/>
      </inertial>
    </link>

    <!-- Camera optical frame (REP-103 compliant) -->
    <joint name="${prefix}camera_optical_joint" type="fixed">
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_link_optical"/>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="${prefix}camera_link_optical"/>

    <!-- ============================================================== -->
    <!-- ARM MOUNTING POINT -->
    <!-- ============================================================== -->

    <joint name="${prefix}arm_mount_joint" type="fixed">
      <parent link="${prefix}body_link"/>
      <child link="${prefix}arm_mount_link"/>
      <!-- Mount arm slightly behind center, on top of chassis -->
      <origin xyz="-0.05 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}arm_mount_link"/>

  </xacro:macro>

</robot>
